# Basic simulation params
fit_data: ../data2/out/SRR*/transcripts.fasta
count: 50000
seed: 487
tree_generator:
  name: extended_birth_death_tree
  params:
    birth_rate: 1.0
    death_rate: 0.5
    extend_relative: 0.1
seq_len_distribution:
  name: match
char_generator:
  name: hky85
  params:
    mutation_rate: 0.01
log_level: DEBUG
save_tree: "phylogeny.tree"
seqid_template: "NODE_cov_{cov}_g{gene}_i{iso}"
separate_dirs: True
coverage_distribution:
  name: uniform
  params:
    min: 0
    max: 10000
# Hybrid params
select: 2
# Divergence params
diverged_taxa: 4
