fit_data: ../data2/out/SRR*/transcripts.fasta
count: 50000
seed: 487
tree_generator:
  name: birth_death_tree
  params:
    birth_rate: 1.0
    death_rate: 0.5
seq_len_distribution:
  name: match
char_generator:
  name: hky85
  params:
    mutation_rate: 0.01
log_level: DEBUG
save_tree: "phylogeny.tree"
seqid_template: "NODE_cov_{cov}_g{gene}_i{iso}"
separate_dirs: True
random_cov:
  max: 10000
